######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 22 15:02:08 2017
######################################################################

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .
QT += network
QT += widgets

# Input
HEADERS += main.hh
SOURCES += main.cc
